# file: mysql/tasks/install.yml

- name: Add mysql apt key
  apt_key: data="{{ mysql_apt_key }}" state=present
  when: mysql_apt_key != False and mysql_apt_key != ""

- name: Add APT repository
  apt_repository: repo="{{mysql_ppa}}" update_cache=yes
  when: mysql_ppa != False and mysql_ppa != ""

- name: Make sure the MySQL packages are installed
  apt:
    pkg: "{{ mysql_packages }}"
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
